[package]
name = "fab-agon-emulator"
version = "0.7.3"
edition = "2021"
authors = ["Tom Morton <tomm8086@gmail.com>"]
license = "BSD-3-Clause"
keywords = ["Agon Light", "Agon Console8", "emulator"]
homepage = "https://github.com/tomm/fab-agon-emulator"
repository = "https://github.com/tomm/fab-agon-emulator"

[dependencies]
sdl2 = "0.35.2"
pico-args = "0.5.0"
agon-cpu-emulator = { git = "https://github.com/tomm/agon-cpu-emulator.git", rev="836a74b87a0750d0ffbfa8a0aa4b9e07aab45dd2"}
agon-light-emulator-debugger = { git = "https://github.com/tomm/agon-light-emulator-debugger.git", rev="43c2dde09d193800d938f4ec1f62fa813fdbddb7"}
libloading = "0.8.0"

#agon-cpu-emulator = { path = "../agon-cpu-emulator" }
#agon-light-emulator-debugger = { path = "../agon-light-emulator-debugger" }
