[package]
name = "fab-agon-emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "*"
agon-cpu-emulator = { path="../agon-cpu-emulator" }

[build-dependencies]
cc = "1.0"
